### ISSUE TITLE
Add luminosity and gamma parameters

### ISSUE THREAD

**Issue by ochurlaud** [kotelnik/plasma-applet-redshift-control#1]
The previous one (https://github.com/simgunz/redshift-plasmoid/) could modify theses parameters.

**Comment by kotelnik** [comment]
Will do. I just wanted to get it out as soon as it was somehow working :)

**Comment by ochurlaud** [comment]
Again, check the porting branch... In src/applet, I did the design for this, but didn't know how to link it to redshift... You might gain some time...

**Comment by kotelnik** [comment]
Thanks! Used some of that setting of yours:) There is just a few settings missing like method and location provider but I would open another issue for that if someone is actually missing those...
