### ISSUE TITLE
New instance of redshift is executed if plasma crashes

### ISSUE THREAD

**Issue by simgunz** [kotelnik/plasma-applet-redshift-control#10]
When plasma crashes and restart, a new instance of redshift is executed causing interference with the previous one, i.e., the color of the screen starts to flicker. There should be a check to verify that other instances of redshift are not already running, and possibly kill them before lunching a new instance or try to use the running instance.

Step to reproduce it:

    kquitapp5 plasmashell
    plasmashell

**Comment by kotelnik** [comment]
I cannot reproduce this behaviour with the above commands.

And I've already considered and tested this use-case. Every time widget is starting a redshift process it kills the previous one.

How exactly does the flickering look like? Is it a persistent flickering or it just changes colour to cold and back to red? Does actually exist more then one instance of redshift in the list of running processes?

**Comment by kotelnik** [comment]
Just to be sure, please check that you have only one instance of widget added to your panel/desktop/systray.

**Comment by simgunz** [comment]
So I've removed redshift from the tray, and no other redshift plasmoids are present. Now when I launch plasmashell only one instance is executed (by plasmashell). So there must be something else that is launching redshift. Probably it's unrelated from your plasmoid.
I'll try to debug this myself.

**Comment by kotelnik** [comment]
That's strange. Can you please also check the number (if there is one) showed on widget icon in "Add Widgets..." -> "Widgets" menu? Another idea - do you have more then one systray added in panel / desktop?

**Comment by simgunz** [comment]
Found the problem. There were two overlapped panels, and the hidden one had the running plasmoid in it. The widget counter was an useful hint to detect the problem. Thanks for the help.

**Comment by kotelnik** [comment]
No problem, I'm glad you found the cause :)
