### ISSUE TITLE
Obsolete advanced options screen

### ISSUE THREAD

**Issue by jkufner** [kotelnik/plasma-applet-redshift-control#13]
Good morning,

mode settings on the screenshot below is obsolete. The preserve option does not work and screen option is missing.

![screenshot1](https://cloud.githubusercontent.com/assets/16572/13376421/3dea5e34-ddbc-11e5-822b-be8956e13f33.png)

```
# redshift -m list
Available adjustment methods:
  drm
  randr
  vidmode
  dummy

Specify colon-separated options with `-m METHOD:OPTIONS'.
Try `-m METHOD:help' for help.
# redshift -m drm:help
Adjust gamma ramps with Direct Rendering Manager.

  card=N        Graphics card to apply adjustments to
  crtc=N        CRTC to apply adjustments to

# redshift -m randr:help
Adjust gamma ramps with the X RANDR extension.

  screen=N      X screen to apply adjustments to
  crtc=N        CRTC to apply adjustments to

# redshift -m vidmode:help
Adjust gamma ramps with the X VidMode extension.

  screen=N      X screen to apply adjustments to

# redshift -m dummy:help
Does not affect the display but prints the color temperature to the terminal.
```

As we can see, there are three options: `card`, `screen` and `crtc`. None of them are available in the plasmoid. I find `screen` option very useful when using projector as a second display.

```
redshift version:  1.10
plasmoid version:  1.0.12-1
(both from Debian packages)
```

Thank you and have a nice day!

**Comment by kotelnik** [comment]
Thanks for the report! I'll try to update the settings according to latest redshift version.

**Comment by kotelnik** [comment]
OK, as I'm working on the gui to change options I can see that currently implemented preserve option cannot work for you since it was introduced with redshift 1.11. Anyway I'll try to make the options dynamically available according underlying redshift version.

**Comment by kotelnik** [comment]
Well it is not so dynamic in the end but it's still an improvement. Please check out the latest version. Preserve option is hidden for users having redshift version less then 1.11.

**Comment by jkufner** [comment]
Thank you. Will check it once it bubbles into Debian repositorires.

**Comment by jkufner** [comment]
I like the future proof manual mode. Works good now. Thank you.

**Comment by kotelnik** [comment]
I'm glad it works for you :).
