### ISSUE TITLE
No longer has temporary disable "lightbulb" control in Plasma 5.5.5

### ISSUE THREAD

**Issue by xenithorb** [kotelnik/plasma-applet-redshift-control#14]
![redshift_no_controls](https://cloud.githubusercontent.com/assets/10273878/13624502/b0c1cb6e-e57c-11e5-88d2-b493249d101b.png)

1. OS: Fedora 23 full updated
1. plasma-desktop-5.5.5-1.fc23.x86_64
1. Redshift still works, options from the settings menu still work.
2. Control is not simply invisible, click action in "correct" area also does nothing.
3. Searched journalctl for some errors, nothing
4. ~/.xsession-errors had:
    ```
    file:///home/xenith/.local/share/plasma/plasmoids/org.kde.redshiftControl/contents/ui/main.qml: QML Plasmoid: Cannot anchor to an item that isn't a parent or sibling.
    ```
    but that seems pretty normal and benign, i've seen it before on F23 pretty often with other applets

**Comment by kotelnik** [comment]
Thanks for this report! I'll fix it.

**Comment by kotelnik** [comment]
Fixed in commit https://github.com/kotelnik/plasma-applet-redshift-control/commit/42234b50449615482bcfb04282cd0992717cc10d

Please reopen if it didn't work out for you.

**Comment by xenithorb** [comment]
I can comfirm that this worked.

I did, for some reason, need to remove `org.kde.redshiftControl` from `~/.local/share/plasma/plasmoids/` though. Simply trying to update from the widgets installer didn't work out.

**Comment by kotelnik** [comment]
Thanks! Yes it's a known and reported bug in Plasma so it will be fixed eventually.
