### ISSUE TITLE
Add localization support.

### ISSUE THREAD

**Issue by s8321414** [kotelnik/plasma-applet-redshift-control#16]
Please add localization support so we can make more non-english user happy :smiley:

**Comment by kotelnik** [comment]
Hi! I've finally got to it. Please look in here:
https://github.com/kotelnik/plasma-applet-redshift-control/tree/master/translations

...and check if it is prepared alright or if it needs some adjustments. Thank You!

**Comment by s8321414** [comment]
Oh good, thank you!

**Comment by s8321414** [comment]
hm, I'm curious about why put .po outside from /po folder...

**Comment by kotelnik** [comment]
This is exactly what I was talking about - I needed a fresh look on this issue. I'll put them to the po folder. It makes sense. Thanks for feedback! :) And again thanks for your translations!

**Comment by s8321414** [comment]
Wonderful, thank you!
