### ISSUE TITLE
Redshift is turned off when I log in

### ISSUE THREAD

**Issue by lunarrunner** [kotelnik/plasma-applet-redshift-control#22]
I have Redshift Control V1.0.16 installed from KDE-Apps.org (using Plasma's widget explorer) and when I log in, Redshift is disabled although Autostart is checked in the plasmoid settings.

I am using Plasma 5.6.4 under Manjaro Linux.

**Comment by Wuxiangdong** [comment]
It works normally on Plasma 5.6.4,archlinux.
Do you remember what you did before it didn't work normally? :)

**Comment by lunarrunner** [comment]
If I remember correctly, I had to reinstall Manjaro around the end of March (due to SSD problems) and I installed Redshift Control from the [AUR](https://aur.archlinux.org/packages/plasma5-applets-redshift-control-git/). I believe that was the first time I noticed this behaviour. (I admit, I should've asked earlier.) Then, I tried installing the latest stable from Plasma's widget explorer, but the issue would still persist.

**Comment by Wuxiangdong** [comment]
I noticed this behaviour this year but I don't remember how I solved it ...
maybe you can try rechecking the checkbox..

**Comment by Wuxiangdong** [comment]
Oh I know ,you are using V1.0.16. 
I am using V1.0.17.please try the lastest version :)

**Comment by lunarrunner** [comment]
Thank you for the advice! I've just realised that whenever I install the AUR package always the latest git version is compiled regardless of what date the AUR says for "Last Updated". So reinstalling the AUR package did the trick.
