### ISSUE TITLE
Location setting lost on reboot irregularly

### ISSUE THREAD

**Issue by khanson679** [kotelnik/plasma-applet-redshift-control#23]
Sometimes the saved latitude and longitude are reset to the default values.

This does not happen every time, and I can't yet find any pattern.
I suspected it might happen when I boot the computer and log in with no network connection,
but I just tested this and the settings were saved this time.

Computer info:
Hardware: Lenovo X250 (Core i5, gen 5)
OS: Kubuntu 16.04 (using kubuntu-backports PPA)
KDE: Plasma 5.6.5, Frameworks 5.23.0, Qt 5.5.1

IIRC the problem occurred on stock Kubuntu 16.04 as well.

**Comment by kotelnik** [comment]
I have a suspicion it has something to do with system tray. Do you have these issues also when placing the widget in panel outside of the systray?

**Comment by khanson679** [comment]
Sorry for the very late reply. I've put an instance of the widget on my desktop, and will report back later. Incidentally, the systray widget hasn't reset recently, so I will give it a couple weeks.

**Comment by kupiqu** [comment]
This is an upstream bug: https://bugs.kde.org/show_bug.cgi?id=365618
The fix is to appear in Plasma 5.8

**Comment by khanson679** [comment]
I see. In that case, nothing more to do here?

**Comment by kupiqu** [comment]
In the meantime, what I do to avoid this problem is to always unlock the desktop, do changes in system settings and lock again.

I think plasma 5.8 will arrive soon enough... :)

**Comment by kotelnik** [comment]
I'm closing this since it should be fixed (or have been) in Plasma.
