### ISSUE TITLE
The temperature is not updated in the plasma applet when it changes at night.

### ISSUE THREAD

**Issue by crocket** [kotelnik/plasma-applet-redshift-control#24]
## The version of the plasma applet

e5ead26
## Description

At night, the temperature drops from 6500k to 3700k.
If I hover the mouse cursor over the applet at night, the reported temperature on the applet's tooltip is still 6500k. The actual temperature is 3700k.

Is it a communication issue between redshift and the plasma applet?

**Comment by kotelnik** [comment]
Thanks for report! I didn't noticed it yet but I'll investigate and try to fix it.

**Comment by kotelnik** [comment]
Sorry about my late response - until now I still cannot reproduce it. Is it still happening? And is this happening consistently or sometimes?

**Comment by crocket** [comment]
I no longer use KDE. I might use it in the future, though. I'll open the issue again if the issue occurs when I use KDE.
