### ISSUE TITLE
Themed or Custom Icon Support

### ISSUE THREAD

**Issue by AndydeCleyre** [kotelnik/plasma-applet-redshift-control#25]
Hi,

Thanks for this applet!

I'd like the option to use status icons from the user's icon theme, rather than fontawesome -- or simply custom icons, one for each status.

At least on Arch, the redshift package itself includes

```
/usr/share/icons/hicolor/scalable/apps/redshift-status-{on,off}.svg
```

And I can see that some other icon themes have the same-named icons as well, like

```
/usr/share/icons/Numix/{16,22,24}/panel/redshift-status-{on,off}.svg
/usr/share/icons/Papirus-GTK/{22x22,24x24}/panel/redshift-status-on.svg
```

**Comment by kotelnik** [comment]
Hi! You're right thats a good idea! I'll add the support. :)

**Comment by Fuhrmann** [comment]
Came here to request this feature. I've increased my panel height and the icon is too big:

![screenshot_20170122_201631](https://cloud.githubusercontent.com/assets/1160365/22187123/b2ecfa8a-e0df-11e6-84d2-e272aa252b12.png)

**Comment by kotelnik** [comment]
Done, hopefully it meets your expectations :). Please reopen this issue if problems occur.
