### ISSUE TITLE
better handling of manual adjustment

### ISSUE THREAD

**Issue by wolftune** [kotelnik/plasma-applet-redshift-control#26]
The scroll-wheel effect that manually overrides the auto settings should:
- start at the current setting (whatever that is) and go redder or bluer from there (depending on scroll direction). Currently it jumps back to 6500 and then adjusts from there.
- revert to the auto settings when the icon is clicked. Currently, it turns off when clicked, requiring two clicks to cycle from manual-override to off and then back on to auto.

**Comment by maxigaz** [comment]
I second the suggestion.

**Comment by kotelnik** [comment]
Sorry for my late response. Thanks for good suggestions, done. Please reopen when problems arise :).

**Comment by wolftune** [comment]
Thanks! Is there any step needed to get the update into Neon repos, or does that happen automatically or something?

**Comment by kotelnik** [comment]
Today I'll submit more code and make a tag. From this point the maintainer of this widget for Debian is able to pull this new version to the sid repos (maybe in matter of days) and I suppose it will shortly be available in Neon then. I'm just not sure whether all flavours of Neon will pick it up right away or if just the Developer one will.

**Comment by ArchangeGabriel** [comment]
I’ve seen more code, but what happened to making a tag? :)

**Comment by kotelnik** [comment]
Sorry, I got myself delayed to squeeze more improvements to the new version. Done now :).

**Comment by maxigaz** [comment]
You are awesome! Together with these changes and hotkey support, the plasmoid is now perfect for my needs. Thank you so much!

**Comment by ArchangeGabriel** [comment]
@kotelnik Thanks! I’ve packaged a stable version for Arch (I saw you already manage -git ones) at https://aur.archlinux.org/packages/plasma5-applets-redshift-control/, that I intend to move into [community].

Many thanks for all your great work on those Plasma Applets. :)

**Comment by kotelnik** [comment]
Thanks for all the positive words! And thanks for the stable packaging :).

**Comment by wolftune** [comment]
I'm confused about how to get this update in KDE Neon. I'm still on 1.0.16 (which is newer than the thing I see listed in the normal xenial repo, so not sure how I got that). Perhaps there's some way to get the KDE Neon folks to update in a way that I and other users will just get the update?

**Comment by kotelnik** [comment]
Unfortunately I don't yet use Neon so I currently cannot help with that. One sure way of course is compile and install it from sources. Please, if you know of a proper channel I should distribute the updates (other then releasing a new version here on github), please let me know :).

**Comment by wolftune** [comment]
I think the best answer is just https://bugs.kde.org/enter_bug.cgi?product=neon and I went and entered this: https://bugs.kde.org/show_bug.cgi?id=383816

**Comment by apachelogger** [comment]
KDE neon does not build third party software. If the applet were to become a proper KDE project it would be a different story of course ;)

To become a KDE project you would have to go through incubation: https://community.kde.org/Incubator

**Comment by wolftune** [comment]
Do it! This obviously is a strictly-KDE piece of software. Join the formal KDE project and get all the benefits and support from the community!
