### ISSUE TITLE
sometimes loses settings

### ISSUE THREAD

**Issue by wolftune** [kotelnik/plasma-applet-redshift-control#27]
I'm not sure when it happens, but I've had the control widget successfully stay as set ever after some log out or reboot or something. But I've also had it lose the settings several times. Not sure if it's when I adjust something in my plasma panel or upon physical reboot of the machine or what. Anyway, there's definitely an issue where settings can be lost. I would guess they aren't being stored in a reliable config file.

**Comment by kupiqu** [comment]
Look issue #23

**Comment by wolftune** [comment]
Thanks
