### ISSUE TITLE
[miniature pannel] Change on click

### ISSUE THREAD

**Issue by ochurlaud** [kotelnik/plasma-applet-redshift-control#3]
Currently, in the miniature pannel, clicking opens a popup where there is just one icon... It would be better, not to popup anything.

When you click, it change the status.

**Comment by kotelnik** [comment]
That was my first intention but I just couldn't come up with a way to do it. It seems onClicked action is overridden by the system-tray in Plasma 5. But I'll try to figure it out... For now left click works only when you put this plasmoid to panel (outside system-tray).

**Comment by ochurlaud** [comment]
See here: https://github.com/simgunz/redshift-plasmoid/blob/plasma5-porting/src/applet/package/contents/ui/

I began to do a porting but didn't go far.... My compactRepresentation was a mouseArea....

**Comment by kotelnik** [comment]
Thanks. I tried to do it as the MouseArea (and various other ways) but my clicked-event was still stolen by the system tray... So for now I'm stuck on this. If you by any chance will have an idea/solution please let me know :)

**Comment by kotelnik** [comment]
I've also asked in KDE forums (https://forum.kde.org/viewtopic.php?f=64&t=127451) about the left click in systray but no answer so far...

**Comment by ochurlaud** [comment]
The Middleton click si good enough

**Comment by kotelnik** [comment]
System tray in Plasma got rewritten (by Marco Martin I believe) so that left-click is handled by plasmoids themselves. As soon as this version of Plasma is released I'll make use of that.

**Comment by kotelnik** [comment]
In the latest commits redshift plasmoid is left-clickable in tray. Please reopen this issue if it misbehave :).
