### ISSUE TITLE
Keyboard shortcut to turn it on and off

### ISSUE THREAD

**Issue by Tamriel** [kotelnik/plasma-applet-redshift-control#30]

**Comment by kotelnik** [comment]
I don't think this is possible right now. I managed to only trigger something by a shortcut when the widget is focused.

**Comment by Tamriel** [comment]
https://github.com/keepassxreboot/keepassxc is able to recognize global shortcuts.

**Comment by kotelnik** [comment]
Thanks for the link. This is rather a standalone application, these are able to expose global shortcuts. But plasmoids are more under control of plasmashell.

Anyway I've just noticed that every plasmoid can have one dedicated global shorctut set in plasmoid settings. This shortcut is activating the plasmoid's state which is by default bringing up plasmoid's popup. But it can be overridden in plasmoid code, so I've overridden the behaviour to toggle redshift state.

Does it now behave as expected?

**Comment by Tamriel** [comment]
Somehow these shortcuts don't work on my system with any plasmoid. Maybe in the future. Thanks!
