### ISSUE TITLE
Allow to disable geoclue

### ISSUE THREAD

**Issue by akien-mga** [kotelnik/plasma-applet-redshift-control#33]
My system usually starts without networking (due to a misconfiguration somewhere, I need to give kwallet my password before it starts the Wi-Fi, but that's another topic). Anyway, it makes Redshift Control fail at each Plasma session start since geoclue can't find the network.

It would be nice if the geolocation could be made optional in the settings, and when disabled, only the manually specified coordinates would be used.

**Comment by kotelnik** [comment]
I believe that automatic geolocation (geoclue) is already optional. In fact it is disabled by default. Check out Redshift Control Settings, section Advanced -> Location. There is a button "Locate" to manually set determine and your location (click it and wait a moment), then you can click Apply and redshift will use that information.

**Comment by akien-mga** [comment]
That works, yes, but it still runs geoclue2 on startup apparently. I can take a screenshot of the error dialog tomorrow when I boot my laptop :)

**Comment by akien-mga** [comment]
Here's the error dialog I get when starting plasma without WiFi connection:
![spectacle w10093](https://cloud.githubusercontent.com/assets/4701338/23054962/3e8bf08e-f4e3-11e6-8f26-e86dbf120109.png)

Even then, Redshift Control still starts and works fine, but this error is annoying :)

**Comment by ArchangeGabriel** [comment]
That’s very strange. I never have any connection on startup (by design/choice), but I don’t have this issue.

However, I have the issue that redshift (sometimes?) doesn’t seems to pick my location once network is back. But maybe that’s because I need to configure it.

**Comment by akien-mga** [comment]
Hm, I think this error actually comes from redshift-gtk... /me hides in shame.

It just appeared when I started using Redshift Control instead, I guess having the GTK+ systray util and the Plasma applet at the same time causes some conflicts. Anyway, not a bug :)
