### ISSUE TITLE
 redshift print finished with code 0, but not matched the regex

### ISSUE THREAD

**Issue by naraesk** [kotelnik/plasma-applet-redshift-control#40]
The following message is printed to my systemd log every 10 seconds:

> plasmashell[22250]: qml: redshift print finished with code 0. sourceName: redshift -t 6500:4000 -b 1:1 -g 1:1:1 -r -p, data: Dienst »geoclue2« wird benutzt.
                                          Zeitraum: Übergang (85.38% day)
                                          Farbtemperatur: 6134K
                                          Helligkeit: 1.00
                                          , but not matched the regex

Is it because the output is localized? How can I change this?

**Comment by kotelnik** [comment]
Yes, it is because of the localization. This problem was already fixed in latest versions. What version of this widget are you using? The latest one is 1.0.18.

**Comment by naraesk** [comment]
Indeed it is fixed. Just found out, that I had two version installed (1.0.14 and 1.0.18). After removing the old one, 1.0.18 is now used and the bug is gone.
