### ISSUE TITLE
Error running Redshift command

### ISSUE THREAD

**Issue by NestorAcevedo** [kotelnik/plasma-applet-redshift-control#41]
I have installed this plasmoid on OpenSUSE TW but when the plasmoid is installed immediately I get the following error: 
Error running Redshift command
/bin/sh: redshift: could not find the order 

Do I need some additional?

**Comment by Wuxiangdong** [comment]
Maybe you need to install redshift

**Comment by NestorAcevedo** [comment]
You're right.
I didn't knew about redshift
