### ISSUE TITLE
Please add versioned tags

### ISSUE THREAD

**Issue by OdyX** [kotelnik/plasma-applet-redshift-control#5]
Please push git tags corresponding to your KDE-Apps versions, this helps packaging.

**Comment by mrueg** [comment]
:+1:

**Comment by kotelnik** [comment]
I will. Until now I was too lazy to learn how to do it :)

**Comment by kotelnik** [comment]
Done. Please let me know if I've done something wrong...

**Comment by OdyX** [comment]
All fine, thanks.
