### ISSUE TITLE
Please specify license in the source

### ISSUE THREAD

**Issue by OdyX** [kotelnik/plasma-applet-redshift-control#8]
While packaging this applet for Debian, it got noticed that the license is not overly explicit; could you add a LICENSE fie at the root of this package?

**Comment by kotelnik** [comment]
Sure, here it is for v1.0.8 :)

**Comment by OdyX** [comment]
So as there are no other headers, is this GPL-2+, or plain GPL-2 ?

**Comment by kotelnik** [comment]
Is there a way to specify it in LICENSE file? I want GPL-2+ which is stated in some of the .qml files. But I'm really a beginner in this stuff.

**Comment by akien-mga** [comment]
Typically you would put a header in all code files, which can be made explicit about the "or any later version". See the headers proposed in https://www.gnu.org/licenses/gpl-howto.html (both the generic "This program is" and specific "Foobar is"). You basically just need to pick one and replace "3" by "2" for GPL-2+.

**Comment by kotelnik** [comment]
Thanks! I've done that now :). Closing thins but please reopen if needed.
