### ISSUE TITLE
icon too big

### ISSUE THREAD

**Issue by mhinsch** [kotelnik/plasma-applet-redshift-control#9]
For my specific settings (ubuntu wily, plasma 5.4.3, screen resolution 3200x1800) if I add the plasmoid to a panel the icon is far too big. I solved the problem by:

a) using font.pixelSize instead of font.pointSize and 
b) making the size of the icon dependent on the minimum of the parents' width and height (instead of asking for vertical)

**Comment by kotelnik** [comment]
Thanks for reporting and especially for these suggestions how to fix it! I'll commit a fix as soon as possible.

**Comment by kotelnik** [comment]
Please try the latest commit. Is that working as expected?
